"""Pattern definitions for Game of Life showcase.

Each pattern has:
- name: Display name
- cells: List of (x, y) coordinates
- duration: Seconds to show this pattern
- description: Brief description
- generations: Keep LOW for slow, visible animation (~2-4 gen/sec)
- grid_size: Optional override for calculated grid size
"""

from dataclasses import dataclass
from typing import List, Tuple


@dataclass
class Pattern:
    name: str
    cells: List[Tuple[int, int]]
    duration: float
    description: str
    generations: int = 10
    grid_size: int | None = None


# Pattern definitions (simple to complex)
PATTERNS = [
    # === Simple Oscillators ===
    Pattern(
        name="Blinker",
        cells=[(0, 0), (1, 0), (2, 0)],
        duration=3.0,
        description="Simplest oscillator (period 2)",
        generations=10,
    ),
    Pattern(
        name="Toad",
        cells=[(1, 0), (2, 0), (3, 0), (0, 1), (1, 1), (2, 1)],
        duration=3.0,
        description="Period 2 oscillator",
        generations=10,
    ),
    Pattern(
        name="Beacon",
        cells=[(0, 0), (1, 0), (0, 1), (3, 2), (2, 3), (3, 3)],
        duration=3.0,
        description="Period 2 oscillator",
        generations=10,
    ),
    Pattern(
        name="Clock",
        cells=[(2, 0), (0, 1), (3, 1), (0, 2), (3, 2), (1, 3)],
        duration=3.0,
        description="Period 2 oscillator",
        generations=10,
    ),
    # === Spaceships ===
    Pattern(
        name="Glider",
        cells=[(1, 0), (2, 1), (0, 2), (1, 2), (2, 2)],
        duration=5.0,
        description="Smallest spaceship, moves diagonally",
        generations=20,
    ),
    Pattern(
        name="Lightweight Spaceship",
        cells=[(1, 0), (4, 0), (0, 1), (0, 2), (4, 2), (0, 3), (1, 3), (2, 3), (3, 3)],
        duration=5.0,
        description="LWSS - moves horizontally",
        generations=16,
    ),
    Pattern(
        name="Middleweight Spaceship",
        cells=[
            (2, 0),
            (0, 1),
            (4, 1),
            (5, 2),
            (0, 3),
            (5, 3),
            (1, 4),
            (2, 4),
            (3, 4),
            (4, 4),
            (5, 4),
        ],
        duration=5.0,
        description="MWSS - moves horizontally",
        generations=16,
    ),
    Pattern(
        name="Heavyweight Spaceship",
        cells=[
            (2, 0),
            (3, 0),
            (0, 1),
            (5, 1),
            (6, 2),
            (0, 3),
            (6, 3),
            (1, 4),
            (2, 4),
            (3, 4),
            (4, 4),
            (5, 4),
            (6, 4),
        ],
        duration=5.0,
        description="HWSS - largest common spaceship",
        generations=16,
    ),
    # === Larger Oscillators ===
    Pattern(
        name="Figure Eight",
        cells=[
            (0, 0),
            (1, 0),
            (2, 0),
            (0, 1),
            (1, 1),
            (2, 1),
            (0, 2),
            (1, 2),
            (2, 2),
            (3, 3),
            (4, 3),
            (5, 3),
            (3, 4),
            (4, 4),
            (5, 4),
            (3, 5),
            (4, 5),
            (5, 5),
        ],
        duration=5.0,
        description="Period 8 oscillator",
        generations=24,
    ),
    Pattern(
        name="Kok's Galaxy",
        cells=[
            (0, 0),
            (1, 0),
            (2, 0),
            (3, 0),
            (4, 0),
            (5, 0),
            (7, 0),
            (8, 0),
            (0, 1),
            (1, 1),
            (2, 1),
            (3, 1),
            (4, 1),
            (5, 1),
            (7, 1),
            (8, 1),
            (7, 2),
            (8, 2),
            (0, 3),
            (1, 3),
            (7, 3),
            (8, 3),
            (0, 4),
            (1, 4),
            (7, 4),
            (8, 4),
            (0, 5),
            (1, 5),
            (7, 5),
            (8, 5),
            (0, 6),
            (1, 6),
            (0, 7),
            (1, 7),
            (3, 7),
            (4, 7),
            (5, 7),
            (6, 7),
            (7, 7),
            (8, 7),
            (0, 8),
            (1, 8),
            (3, 8),
            (4, 8),
            (5, 8),
            (6, 8),
            (7, 8),
            (8, 8),
        ],
        duration=5.0,
        description="Period 8 oscillator",
        generations=24,
    ),
    Pattern(
        name="Tumbler",
        cells=[
            (1, 0),
            (2, 0),
            (4, 0),
            (5, 0),
            (1, 1),
            (2, 1),
            (4, 1),
            (5, 1),
            (2, 2),
            (4, 2),
            (0, 3),
            (2, 3),
            (4, 3),
            (6, 3),
            (0, 4),
            (2, 4),
            (4, 4),
            (6, 4),
            (0, 5),
            (1, 5),
            (5, 5),
            (6, 5),
        ],
        duration=6.0,
        description="Period 14 oscillator",
        generations=28,
    ),
    Pattern(
        name="Pulsar",
        cells=[
            (2, 0),
            (3, 0),
            (4, 0),
            (8, 0),
            (9, 0),
            (10, 0),
            (0, 2),
            (5, 2),
            (7, 2),
            (12, 2),
            (0, 3),
            (5, 3),
            (7, 3),
            (12, 3),
            (0, 4),
            (5, 4),
            (7, 4),
            (12, 4),
            (2, 5),
            (3, 5),
            (4, 5),
            (8, 5),
            (9, 5),
            (10, 5),
            (2, 7),
            (3, 7),
            (4, 7),
            (8, 7),
            (9, 7),
            (10, 7),
            (0, 8),
            (5, 8),
            (7, 8),
            (12, 8),
            (0, 9),
            (5, 9),
            (7, 9),
            (12, 9),
            (0, 10),
            (5, 10),
            (7, 10),
            (12, 10),
            (2, 12),
            (3, 12),
            (4, 12),
            (8, 12),
            (9, 12),
            (10, 12),
        ],
        duration=5.0,
        description="Period 3 oscillator",
        generations=15,
    ),
    Pattern(
        name="Pentadecathlon",
        cells=[(i, 0) for i in range(10)],
        duration=6.0,
        description="Period 15 oscillator",
        generations=30,
    ),
    # === Methuselahs ===
    Pattern(
        name="R-pentomino",
        cells=[(1, 0), (2, 0), (0, 1), (1, 1), (1, 2)],
        duration=8.0,
        description="Methuselah - stabilizes after 1103 generations",
        generations=50,
    ),
    Pattern(
        name="B-heptomino",
        cells=[(0, 0), (2, 0), (3, 0), (0, 1), (1, 1), (2, 1), (1, 2)],
        duration=8.0,
        description="Active methuselah - stabilizes at gen 148",
        generations=60,
    ),
    Pattern(
        name="Pi-heptomino",
        cells=[
            (0, 0),
            (1, 0),
            (2, 0),
            (0, 1),
            (2, 1),
            (0, 2),
            (2, 2),
        ],
        duration=6.0,
        description="Methuselah - stabilizes after 173 generations",
        generations=40,
    ),
    Pattern(
        name="Diehard",
        cells=[(6, 0), (0, 1), (1, 1), (1, 2), (5, 2), (6, 2), (7, 2)],
        duration=8.0,
        description="Completely dies after 130 generations",
        generations=65,
    ),
    Pattern(
        name="Acorn",
        cells=[(1, 0), (3, 1), (0, 2), (1, 2), (4, 2), (5, 2), (6, 2)],
        duration=8.0,
        description="Methuselah - 5206 generations to stabilize",
        generations=60,
    ),
    # === Advanced ===
    Pattern(
        name="Puffer Train",
        cells=[
            # LWSS 1
            (1, 0),
            (4, 0),
            (0, 1),
            (0, 2),
            (4, 2),
            (0, 3),
            (1, 3),
            (2, 3),
            (3, 3),
            # Middle part
            (6, 3),
            (7, 3),
            (8, 3),
            (6, 4),
            (8, 4),
            (8, 5),
            (8, 6),
            (7, 7),
            # LWSS 2
            (1, 9),
            (4, 9),
            (0, 10),
            (0, 11),
            (4, 11),
            (0, 12),
            (1, 12),
            (2, 12),
            (3, 12),
        ],
        duration=10.0,
        description="Spaceship that leaves debris behind",
        generations=50,
    ),
    Pattern(
        name="Gosper Glider Gun",
        cells=[
            # Left square
            (0, 4),
            (0, 5),
            (1, 4),
            (1, 5),
            # Left part
            (10, 4),
            (10, 5),
            (10, 6),
            (11, 3),
            (11, 7),
            (12, 2),
            (12, 8),
            (13, 2),
            (13, 8),
            (14, 5),
            (15, 3),
            (15, 7),
            (16, 4),
            (16, 5),
            (16, 6),
            (17, 5),
            # Right part
            (20, 2),
            (20, 3),
            (20, 4),
            (21, 2),
            (21, 3),
            (21, 4),
            (22, 1),
            (22, 5),
            (24, 0),
            (24, 1),
            (24, 5),
            (24, 6),
            # Right square
            (34, 2),
            (34, 3),
            (35, 2),
            (35, 3),
        ],
        duration=12.0,
        description="First known gun - creates gliders every 30 generations",
        generations=70,
    ),
]
